# Generated by Django 5.2.10 on 2026-03-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("laboratory_name", models.CharField(max_length=20)),
                ("laboratory_number", models.CharField(max_length=20)),
                ("laboratory_email", models.EmailField(max_length=20)),
                ("laboratory_otp", models.CharField(max_length=10)),
                ("laboratory_password", models.CharField(max_length=10)),
            ],
        ),
    ]
