# Generated by Django 5.2.10 on 2026-04-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_laboratory"),
    ]

    operations = [
        migrations.AddField(
            model_name="laboratory",
            name="laboratory_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="laboratory",
            name="laboratory_gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="laboratory",
            name="laboratory_image",
            field=models.ImageField(blank=True, null=True, upload_to="laboratory/"),
        ),
        migrations.AddField(
            model_name="laboratory",
            name="laboratory_speciality",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
