# Generated by Django 5.2.10 on 2026-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_laboratory_laboratory_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
